full: true
plugins:
  - cleanupAttrs:
      newlines: false
#  - removeDoctype
#  - removeXMLProcInst
  - removeComments
  - removeMetadata
#  - removeTitle
#  - removeDesc
#  - removeUselessDefs
#  - removeEditorsNSData
#  - removeEmptyAttrs
#  - removeHiddenElems
#  - removeEmptyText
#  - removeEmptyContainers
#  - removeViewBox
#  - cleanUpEnableBackground
#  - convertStyleToAttrs
#  - convertColors
#  - convertPathData
  - convertTransform
#  - removeUnknownsAndDefaults
#  - removeNonInheritableGroupAttrs
#  - removeUselessStrokeAndFill
#  - removeUnusedNS
#  - cleanupIDs
#  - cleanupNumericValues
#  - moveElemsAttrsToGroup
#  - moveGroupAttrsToElems
#  - collapseGroups
#  - removeRasterImages
#  - mergePaths
#  - convertShapeToPath
#  - sortAttrs
#  - transformsWithOnePath
#  - removeDimensions
#  - removeAttrs:
      #attrs: '(stroke|fill)'